### ISSUE TITLE
msg: chgrp failed: failed to look up group

### ISSUE THREAD

**Issue by gregorskii** [weareinteractive/ansible-users-oh-my-zsh#1]
Hi there,

When running this task against vagrant boxes it fails on the task "Setting permissions".

I am running these tasks before:

```

- franklinkim.apt
- franklinkim.timezone
- franklinkim.users
- franklinkim.users-oh-my-zsh

```

With:

timezone setting "America/Los Angeles"
apt only installing git to download oh my zsh

Users Running:

```

---
users:
  - username: nonroot
    name: NonRoot User
    oh_my_zsh:
      theme: amuse
# Grant sudo to nonroot
sudo_users:
  - { name: 'nonroot', nopasswd: no }

```

I am running the provision outside of vagrant up using this command:

```
ansible-playbook -i hosts_vagrant -u vagrant --private-key=~/.vagrant.d/insecure_private_key site.yml
```

site.yml contains imports to sub playbooks:

```

---
- include: pb_commonsystem.yml
- include: pb_webservers.yml
- include: pb_dbservers.yml
- include: pb_deployservers.yml
- include: pb_monitoring.yml
- include: pb_webserver_monitoring.yml

```

Where the commonsystem looks like this:

```

---
- hosts: all
  sudo: yes
  roles:
    - franklinkim.apt
    - franklinkim.timezone
    - franklinkim.users
    - franklinkim.users-oh-my-zsh
    - franklinkim.sudo
    - franklinkim.ssh
  vars_files:
    - vars/ssh.yml
    - vars/users.yml
    - vars/apt.yml
  vars:
    timezone: 'America/Los Angeles'

```
