### ISSUE TITLE
User as sudoer ?

### ISSUE THREAD

**Issue by anthony-robin** [weareinteractive/ansible-users-oh-my-zsh#4]
Is there a way to define a newly created user to be sudoer (no password required when using sudo command) or this is not the aim of this recipe ?

**Comment by franklinkim** [comment]
hi, no, this is not the purpose of this role. 
Use this role in conjunction with `franklinkim.sudo` [here](https://github.com/weareinteractive/ansible-sudo) to create a `sudo` group and `franklinkim.users` [here](https://github.com/weareinteractive/ansible-users) to create users. ie:

``` yaml
- hosts: all
  become: yes
  become_user: root
  vars:
    sudo_users:
      - { name: '%sudo', nopasswd: yes }
    users:
      - username: foo
        name: Foo bar
        groups: ["sudo"]
  roles:
    - franklinkim.sudo
    - franklinkim.users
    - ...
```

hope that helps
