### ISSUE TITLE
How to install oh-my-zsh for root?

### ISSUE THREAD

**Issue by jiming** [weareinteractive/ansible-users-oh-my-zsh#6]
Thanks!

**Comment by franklinkim** [comment]
Hi, this role currently doesn't support the root user. 

I personally never use the root user and if I have to, I find it better to have the environment as clean as possible

If you wish to add this, we could probably add an option to each user, defining the `user.home` path.

PR's are always welcome

**Comment by jiming** [comment]
Hi Franklinkim,

I use copy have the job done.  

Since root is a special user, I am not sure it should be added in the role. Let's see what other guys say.

If you think it is not necessary, please close the issue.

Thanks a lot!

Jiming

**Comment by franklinkim** [comment]
ok, I'll close it for now. If the topic comes up again, I'll reference this issue.

**Comment by apiening** [comment]
I have the same requirement.
> I use copy have the job done.

Do you mean a manual copy of the .zshrc and .oh-my-zsh from another user to the root user?
If you was able to automate this, can you give an example please?

**Comment by franklinkim** [comment]
Just as a quick a quick sketch (needs testing and default groups might not make sense for root, PR welcome):

New user prop:
```yaml
...
  home: /root
...
```

install.yml
```yaml
- name: Installing oh-my-zsh per user
  git:
    repo: https://github.com/robbyrussell/oh-my-zsh.git
    dest: "{{ item.home | default('/home/' ~ item.username)}}/.oh-my-zsh"
    update: "{{ users_oh_my_zsh_update }}"
  with_items: "{{ users }}"

- name: Setting permissions per user
  file:
    dest: "{{ item.home | default('/home/' ~ item.username)}}/.oh-my-zsh"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else (users_group if users_group else item.username) }}"
    recurse: yes
  with_items: "{{ users }}"

- name: Setting default shell per user
  user:
    name: "{{ item.username }}"
    shell: /bin/zsh
  with_items: "{{ users }}"

- name: Configuring oh-my-zsh
  template:
    src: home-user-zshrc.j2
    dest: "{{ item.home | default('/home/' ~ item.username)}}/.oh-my-zsh"
    owner: "{{ item.username }}"
    group: "{{ item.group if item.group is defined else (users_group if users_group else item.username) }}"
    backup: yes
    mode: "0644"
  with_items: "{{ users }}"
```
